# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7c5064e58eeaa53fe778a48aee0646375db6b41a9bacc16023fc54b84daf5aa2caeb03055366b2c8bc2695463ccb585b7fecb3fe937ba119027226b68bf56e0

test:
  secret_key_base: dcf2c74608b0f94135c3e5be443535ad426e82027b88d399089df79f518a129ab7cde073ef96119ee555544ecbf9ecc6433fc686e793394d141c0b3dc8d80aa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
